[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.20"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ad_marketplace = "GP2BCEo8Ciz7gNBvwB7KMMTTuzAroiHMsdALuNq1q4XB"
payments = "4Gmw6sYgyKB4Ppavaw5AhvkDEXj8EAPftW6DU2AUYBkB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
