[toolchain]
anchor_version = "0.31.0"
solana_version = "2.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ad_marketplace = "FgcY5LgSSEqSdJdUstBefMaZgEtMcAzqDdzDMrU9j5X9"
payments = "3L1ESMJzFuv5tfPSoB1iHptoSndh3dRzpfVn8PRSX5FJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
